name: foodking
version: 1.0.10+10
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.2.0
  flutter_screenutil: ^5.7.0
  image_picker: ^0.8.7+3
  get_storage: ^2.1.1
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  timeline_tile: ^2.0.0
  contained_tab_bar_view: ^0.8.0
  toggle_switch: ^2.0.1
  another_stepper: 
  expansion_tile_card: ^2.0.0
  expandable: ^5.0.1
  country_picker: ^2.0.20
  dropdown_button2: ^1.9.1
  flutter_chat_ui: ^1.6.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^4.3.7
  custom_map_markers: ^0.0.2+1
  connectivity: ^3.0.6
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  flutter_local_notifications: ^9.5.3+1
  flutter_launcher_icons: ^0.13.0
  shared_preferences: ^2.1.0
  rflutter_alert: ^2.0.4
  im_stepper: ^1.0.1+1
  fluttertoast: ^8.2.1
  pinput: ^2.2.31
  flutter_staggered_grid_view: ^0.4.1
  flutter_inappwebview: ^5.7.2+3
  path_provider: ^2.0.14
  map_launcher: ^2.5.0+1
  easy_stepper: ^0.5.2+1

  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  



flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: "ic_launcher"
  ios: true


flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
